name: local_auth_example
description: Demonstrates how to use the local_auth plugin.
publish_to: none
version: 1.0.0+100

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  huawei_fido: ^6.3.0+305
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.3.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
